#!/usr/bin/env python3
import docker_api as docker
from docker.errors import APIError
import json
import query

print("Content-type: text/plain\n")

id = query.parse(['id'])

container = docker.get_container(id)

if not container:
    print('invalid id', end='')
    exit()

try:
    container.start()
    print('ok', end='')
except APIError:
    print('error', end='')
